Fix channel splitting for multiplex tiff (#95)
When trying to open a multiplex tiff (39 channels), a user was getting
this error:
```
File ~/Documents/dev/napari-tiff/.venv/lib/python3.14/site-packages/napari/utils/transforms/transforms.py:469, in Affine.__init__(self=<napari.utils.transforms.transforms.CompositeAffine object>, scale=(0.5065160804676162, 0.5065160804676162), translate=[0, 0, 0], affine_matrix=None, axis_labels=None, linear_matrix=array([[1.     , 0.     , 0.     ],
       [0.  ...2, 0.     ],
       [0.     , 0.     , 0.50652]]), name='data2physical', ndim=3, rotate=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), shear=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), units=('µm', 'µm'))
    466 self._units = (pint.get_application_registry().pixel,) * ndim
    468 self.axis_labels = axis_labels
--> 469 self.units = units
        units = ('µm', 'µm')
        self = <napari.utils.transforms.transforms.CompositeAffine object at 0x129e02e40>
File ~/Documents/dev/napari-tiff/.venv/lib/python3.14/site-packages/napari/utils/transforms/transforms.py:519, in Affine.units(self=<napari.utils.transforms.transforms.CompositeAffine object>, units=(Unit("micrometer"), Unit("micrometer")))
    517     units = (units,) * self.ndim
    518 if len(units) != self.ndim:
--> 519     raise ValueError(f'{units=} must have length ndim={self.ndim}.')
        units = (Unit("micrometer"), Unit("micrometer"))
        self = <napari.utils.transforms.transforms.CompositeAffine object at 0x129e02e40>    520 self._units = units

ValueError: units=(Unit("micrometer"), Unit("micrometer")) must have length ndim=3.
```

Looking at the code we were limiting the number of channels and passing
lists of colormaps. So in this case the channels were not being split
properly.

In this PR I make a minimal fix to lift the limit and let napari handle
colormap iteration, which works out of the box now if you don't pass a
list of colormaps.

Simple test by Claude.